#!/usr/bin/env python
# Triangle, pentagonal, and hexagonal numbers 
# are generated by the following formulae:
# 
# Triangle    Tn=n(n+1)/2.6   1, 3, 6, 10, 15, ...
# Pentagonal  Pn=n(3n1)/2.6   1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n1)       1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also 
# pentagonal and hexagonal.

def triangle(n):
    return n*(n+1)/2

def pentagonal(n):
    return n*(3*n-1)/2

def hexagonal(n):
    return n*(2*n-1)

def main():
    p = set(pentagonal(n) for n in range(100000))
    h = set(hexagonal(n) for n in range(100000))
    for n in range(100000):
        t = triangle(n)
        if t in p and t in h:
            print n, t

if __name__ == "__main__":
    main()
