#!/usr/bin/env python3
# Consider all integer combinations of ab for 2 <= a <= 5 and 2 <= b <= 5:
# 
# 2^2=4, 2^3=8, 2^4=16, 2^5=32 (etc.)
# 32=9, 33=27, 34=81, 35=243
# 42=16, 43=64, 44=256, 45=1024
# 52=25, 53=125, 54=625, 55=3125
# If they are then placed in numerical order, with any repeats removed, we 
# get the following sequence of 15 distinct terms:
# 
# 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
# 
# How many distinct terms are in the sequence generated by a^b for 
# 2 <= a <= 100 and 2 <= b <= 100?
import itertools
sequence = sorted(set(combo[0]**combo[1] for combo in itertools.product(range(2,101), repeat=2)))
print(len(sequence))
